"""Add qa_interaction table

Revision ID: ce3fb8b3d191
Revises: c3363bdf61fa
Create Date: 2024-04-12 13:58:46.916722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce3fb8b3d191'
down_revision: Union[str, None] = 'c3363bdf61fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('assistant_thread_id', sa.String(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('slack_user_id', sa.String(), nullable=True),
    sa.Column('question_timestamp', sa.DateTime(), nullable=True),
    sa.Column('answer_timestamp', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('last_embedded', sa.DateTime(), nullable=True),
    sa.Column('embed', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qa_interactions')
    # ### end Alembic commands ###
