"""Add user_score table

Revision ID: 59b9eced0668
Revises: dccb3577feb5
Create Date: 2024-04-12 14:00:04.186969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59b9eced0668'
down_revision: Union[str, None] = 'dccb3577feb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slack_user_id', sa.String(), nullable=False),
    sa.Column('seeker_score', sa.Integer(), nullable=True),
    sa.Column('revealer_score', sa.Integer(), nullable=True),
    sa.Column('luminary_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slack_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_scores')
    # ### end Alembic commands ###
