"""Add bookmarked_conversation table

Revision ID: c3363bdf61fa
Revises: 4ae5c037da0f
Create Date: 2024-04-12 13:58:12.798686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3363bdf61fa'
down_revision: Union[str, None] = '4ae5c037da0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarked_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('thread_id', sa.String(), nullable=True),
    sa.Column('bookmarked_on_slack', sa.DateTime(), nullable=True),
    sa.Column('posted_on_confluence', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmarked_conversations')
    # ### end Alembic commands ###
