"""Add page_data table

Revision ID: 4ae5c037da0f
Revises: 713caec2649e
Create Date: 2024-04-12 13:57:09.418241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ae5c037da0f'
down_revision: Union[str, None] = '713caec2649e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.String(), nullable=True),
    sa.Column('space_key', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('lastUpdated', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('last_embedded', sa.DateTime(), nullable=True),
    sa.Column('embed', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_data')
    # ### end Alembic commands ###
